#!/bin/bash

sed -e 's/<[^>]*>//g' | sed -e '/^\s*$/d' | tr '[:upper:]' '[:lower:]' | sed -e "s/\`/\'/g" | sed -e '1,5d' | sed -e '425,431d' | sed -e 's/\((.*)\)//g' | tr "," "\n" | sed -e 's/\s\+/\n/g' | sed '/[^p^k^m^n^w^l^h^a^e^i^o^u'\'']/d' | sort | uniq
